In [1]:
import numpy as np
import pandas as pd

In [2]:
# Mileposts of functioning 405 loops from Mark on Slack 7/16/19
# (but there were repeats in NB column, so got rid of those and added 30.06)
loops = pd.read_csv('/opt/dssg-hot/data/milepost_lookups/functioning_loops.csv')
loops.tail()

    NB - both HOT & GP  SB - both HOT & GP
37               27.96               14.63
38               28.53               14.27
39               28.98               13.92
40               29.53               13.31
41               30.06                 NaN

In [3]:
# From trips_lookup_master google sheet tab nb_mileposts_exits_plaza_lookup
nbex = pd.read_csv('/opt/dssg-hot/data/milepost_lookups/nb_mileposts_exits_plaza_lookup.csv')
nbex.head()

,Exit plaza name,Exit plaza number,Actual exit,Mile post (SRweb),Loop mile post before exit,Loop mile post after exit,Loop mile post to take,"Diff btwn loop mile and actual mile post (pos = take before, neg = take after)",Notes
0,NB01,3,NB Entry 3/Exit 1 (midpt),15.76,16.12,15.63,15.63,0.13,NaN
1,NB02,4,NB Entry 3/Exit 1 (midpt),15.76,16.12,15.63,15.63,0.13,NaN
2,NB03,5,NB Entry 4/Exit 2 (midpt),19.12,19.21,18.70,19.21,-0.09,NaN
3,NB04,6,NB Exit 4,21.86,22.31,21.83,21.83,0.03,NaN
4,NB05,7,NB Exit 3 (beginning of off ramp),20.35,20.47,20.22,20.47,-0.12,NaN

In [4]:
# From trips_lookup_master google sheet tab nb_mileposts_entries_plaza_lookup
nben = pd.read_csv('/opt/dssg-hot/data/milepost_lookups/nb_mileposts_entries_plaza_lookup.csv')
nben.head()

,Entry plaza name,Entry plaza number,Actual entry name,Mile post (SRweb),Loop mile post before entry,Loop mile post after entry,Loop mile post to take,"Diff btwn loop mile and actual mile post (pos = take before, neg = take after)",Closest 0.5 mi mp to SRweb mp (or loop mp to take when SRweb mp is missing),Notes
0,NB01,3,NB Entry 1,13.74,13.60,13.92,13.60,0.14,13.5,NaN
1,NB02,4,NB Entry 2 (end of on ramp),13.93,13.92,14.27,13.92,0.01,14.0,NaN
2,NB03,5,NB Entry 3/Exit 1 (midpt),15.76,15.63,16.12,15.63,0.13,16.0,NaN
3,NB04,6,NB Entry 4/Exit 2 (midpt),19.12,18.70,19.21,19.21,-0.09,19.0,NaN
4,NB05,7,NaN,NaN,NaN,NaN,20.22,NaN,20.0,Shouldn't exist as entry --> arbitrarily chose...

In [5]:
# From trips_lookup_master google sheet tab sb_mileposts_exits_plaza_lookup
sbex = pd.read_csv('/opt/dssg-hot/data/milepost_lookups/sb_mileposts_exits_plaza_lookup.csv')
sbex.head()

,Exit plaza name,Exit plaza number,Actual exit,Mile post (SRweb),Loop mile post before entry,Loop mile post after entry,Loop mile post to take,"Diff btwn loop mile and actual mile post (pos = take before, neg = take after)",Notes
0,SB01,13,SB Entry 2/Exit 1 (midpt),27.61,27.96,27.44,27.44,-0.16,NaN
1,SB02,14,SB Entry 3/Exit 2 (midpt),25.95,26.16,25.68,26.16,0.21,NaN
2,SB03,15,NaN,NaN,NaN,NaN,25.17,NaN,Shouldn't exist as exit --> arbitrarily chose ...
3,SB04,16,NaN,NaN,NaN,NaN,21.83,NaN,Shouldn't exist as exit --> arbitrarily chose ...
4,SB05,17,SB Entry 7/Exit 4 (midpt),18.95,19.21,18.70,18.70,-0.25,NaN

In [7]:
# From trips_lookup_master google sheet tab sb_mileposts_entries_plaza_lookup
sben = pd.read_csv('/opt/dssg-hot/data/milepost_lookups/sb_mileposts_entries_plaza_lookup.csv')
sben.head()

,Entry plaza name,Entry plaza number,Actual entry,Mile post (SRweb),Loop mile post before entry,Loop mile post after entry,Loop mile post to take,"Diff btwn loop mile and actual mile post (pos = take before, neg = take after)",Closest 0.5 mi mp to SRweb mp (or loop mp to take when SRweb mp is missing),Notes
0,SB01,13,SB Entry 1,28.89,28.98,28.53,28.98,0.09,29.0,NaN
1,SB02,14,SB Entry 2/Exit 1 (midpt),27.61,27.96,27.44,27.44,-0.16,27.5,NaN
2,SB03,15,SB Entry 3/Exit 2 (midpt),25.95,26.16,25.68,26.16,0.21,26.0,NaN
3,SB04,16,SB Entry 4 (midpt),22.50,22.73,22.31,22.31,-0.19,22.5,NaN
4,SB05,17,SB Entry 5,21.59,21.83,21.36,21.36,-0.23,21.5,NaN

In [8]:
# From trips_lookup_master google sheet tab toll_plaza_mileposts
tps = pd.read_csv('/opt/dssg-hot/data/milepost_lookups/toll_plaza_mileposts.csv',)
tps.head()

  Plaza ID  Plaza Number  Mile Post               Name
0     NB01             3       13.8              start
1     NB02             4       13.8        ramp NE 6th
2     NB03             5       16.7             SR 520
3     NB04             6       19.7           NE 116th
4     NB05             7       20.5  ramp off NE 128th

In [24]:
def findBeforeAfterMP(goodloops,actualmp):
    """Finds the closest fxning loops, before and after the exact milepost denoted by actualmp.
    actualmp is a scalar. goodloops is a pandas series."""
    exactmatch=goodloops[goodloops==actualmp]
    if exactmatch.empty==False:
        return exactmatch.index[0]
    else:
        smallermp = goodloops[goodloops<actualmp].iloc[-1]
        biggermp = goodloops[goodloops>actualmp].iloc[0]
        return smallermp, biggermp

In [42]:
# NB entries
goodloops = loops['NB - both HOT & GP']
gl_nben = goodloops.sort_values(ascending=True)

biggermps_nben = np.zeros(len(nben['Mile post (SRweb)']))
smallermps_nben = np.zeros(len(nben['Mile post (SRweb)']))

for idx in range(0,len(nben['Mile post (SRweb)'])):
    amp = np.asscalar(nben['Mile post (SRweb)'].iloc[[idx]])
    if np.isnan(amp):
        smallermps_nben[idx] = np.nan; biggermps_nben[idx] = np.nan;
    else:
        [smallermps_nben[idx],biggermps_nben[idx]] = findBeforeAfterMP(gl_nben,amp)

print(smallermps_nben)
print(biggermps_nben)

[13.6  13.92 15.63 18.7    nan 20.93   nan 25.17 27.44   nan]
[13.92 14.27 16.12 19.21   nan 21.36   nan 25.68 27.96   nan]

In [43]:
# NB exits
goodloops = loops['NB - both HOT & GP']
gl_nbex = goodloops.sort_values(ascending=True)

biggermps_nbex = np.zeros(len(nbex['Mile post (SRweb)']))
smallermps_nbex = np.zeros(len(nbex['Mile post (SRweb)']))

for idx in range(0,len(nbex['Mile post (SRweb)'])):
    amp = np.asscalar(nbex['Mile post (SRweb)'].iloc[[idx]])
    if np.isnan(amp):
        smallermps_nbex[idx] = np.nan; biggermps_nbex[idx] = np.nan;
    else:
        [smallermps_nbex[idx],biggermps_nbex[idx]] = findBeforeAfterMP(gl_nbex,amp)

print(smallermps_nbex)
print(biggermps_nbex)

[15.63 15.63 18.7  21.83 20.22 21.83 25.17 27.44   nan 28.98]
[16.12 16.12 19.21 22.31 20.47 22.31 25.68 27.96   nan 29.53]

In [44]:
# SB entries
goodloops = loops['SB - both HOT & GP']
gl_sben = goodloops.sort_values(ascending=True)

biggermps_sben = np.zeros(len(sben['Mile post (SRweb)']))
smallermps_sben = np.zeros(len(sben['Mile post (SRweb)']))

for idx in range(0,len(sben['Mile post (SRweb)'])):
    amp = np.asscalar(sben['Mile post (SRweb)'].iloc[[idx]])
    if np.isnan(amp):
        smallermps_sben[idx] = np.nan; biggermps_sben[idx] = np.nan;
    else:
        [biggermps_sben[idx],smallermps_sben[idx]] = findBeforeAfterMP(gl_sben,amp)

print(smallermps_sben)
print(biggermps_sben)

[28.98 27.96 26.16 22.73 21.83   nan 20.47 19.21 16.67   nan   nan]
[28.53 27.44 25.68 22.31 21.36   nan 20.22 18.7  16.12   nan   nan]

In [45]:
# SB exits
goodloops = loops['SB - both HOT & GP']
gl_sbex = goodloops.sort_values(ascending=True)

biggermps_sbex = np.zeros(len(sbex['Mile post (SRweb)']))
smallermps_sbex = np.zeros(len(sbex['Mile post (SRweb)']))

for idx in range(0,len(sbex['Mile post (SRweb)'])):
    amp = np.asscalar(sbex['Mile post (SRweb)'].iloc[[idx]])
    if np.isnan(amp):
        smallermps_sbex[idx] = np.nan; biggermps_sbex[idx] = np.nan;
    else:
        [biggermps_sbex[idx],smallermps_sbex[idx]] = findBeforeAfterMP(gl_sbex,amp)

print(smallermps_sbex)
print(biggermps_sbex)

[27.96 26.16   nan   nan 19.21 20.93 19.21 16.67   nan 13.92 13.92]
[27.44 25.68   nan   nan 18.7  20.47 18.7  16.12   nan 13.31 13.31]

In [51]:
# NB toll plazas
goodloops = loops['NB - both HOT & GP']
gl_nbtps = goodloops.sort_values(ascending=True)

biggermps_tps = np.zeros(len(tps[tps['Plaza Number']<13]['Mile Post']))
smallermps_tps = np.zeros(len(tps[tps['Plaza Number']<13]['Mile Post']))

for idx in range(0,len(tps[tps['Plaza Number']<13]['Mile Post'])):
    amp = np.asscalar(tps[tps['Plaza Number']<13]['Mile Post'].iloc[[idx]])
    [smallermps_tps[idx],biggermps_tps[idx]] = findBeforeAfterMP(gl_nbtps,amp)

print(smallermps_tps)
print(biggermps_tps)

[13.6  13.6  16.67 19.21 20.47 20.47 21.83 25.68 27.96 28.98]
[13.92 13.92 17.23 19.71 20.93 20.93 22.31 26.16 28.53 29.53]

In [54]:
# SB toll plazas
goodloops = loops['SB - both HOT & GP']
gl_sbtps = goodloops.sort_values(ascending=True)

biggermps_tps = np.zeros(len(tps[tps['Plaza Number']>12]['Mile Post']))
smallermps_tps = np.zeros(len(tps[tps['Plaza Number']>12]['Mile Post']))

for idx in range(0,len(tps[tps['Plaza Number']>12]['Mile Post'])):
    amp = np.asscalar(tps[tps['Plaza Number']>12]['Mile Post'].iloc[[idx]])
    [biggermps_tps[idx],smallermps_tps[idx]] = findBeforeAfterMP(gl_sbtps,amp)

print(smallermps_tps)
print(biggermps_tps)

[28.98 27.44 25.68 22.31 21.36 20.93 20.93 17.99 15.63 13.92 13.92]
[28.53 26.88 25.17 21.83 20.93 20.47 20.47 17.49 15.08 13.31 13.31]